CREATE TABLE AUTONUMBER  (
	ROW_ID NUMBER(38) NOT NULL PRIMARY KEY
) ;
/
CREATE TABLE VPDM_MAIN (
	ROW_ID  NUMBER(38) NOT NULL PRIMARY KEY,	
	ID NVARCHAR2(25)  NULL,
	CUSTOMER NVARCHAR2(50)  NULL,
	PARENTID NVARCHAR2(25) NOT NULL,
	PARENTVERSION NUMBER(6) NOT  NULL,
	ISROOT CHAR(1) NOT NULL,
	BOMTYPE CHAR(1)  NULL,
        KEYWORD NVARCHAR2(40)  NULL,
	TAG CHAR(1)  DEFAULT 'N',
	DTS_DATE DATE DEFAULT SYSDATE 
);
/
CREATE TABLE VPDM_PART (
	ROW_ID NUMBER(38)  NOT NULL PRIMARY KEY,
	ID NVARCHAR2 (25) NOT NULL ,
	TYPE CHAR (1) NULL ,
	STATUS CHAR (1) NULL ,
	NAME NVARCHAR2 (50) NULL ,
	ENGLISHNAME NVARCHAR2 (80) NULL ,
	CATEGORY NVARCHAR2 (50) NULL ,
	GROUPPROP NVARCHAR2 (40) NULL ,
	RAWMATERIAL NVARCHAR2 (40) NULL ,
	MATERIAL NVARCHAR2 (40) NULL ,
	HEATTREATMENT NVARCHAR2 (50) NULL ,
	SURFACETREATMENT NVARCHAR2 (50) NULL ,
	CHIUNIT NVARCHAR2 (20) NULL ,
	ENGUNIT NVARCHAR2 (20) NULL ,
	SOP NVARCHAR2 (100) NULL ,
	SPEC NVARCHAR2 (100) NULL ,
	DESCRIPTION CLOB NULL ,
	PRODUCTCODE NVARCHAR2 (20) NULL ,
	COMMODITYCODE NVARCHAR2 (20) NULL ,
	PRODUCTCODENAME NVARCHAR2 (50) NULL ,	
	COMMCODENAME NVARCHAR2 (50) NULL ,
	USER_1 NVARCHAR2 (45) NULL ,
	USER_2 NVARCHAR2 (45) NULL ,
	USER_3 NVARCHAR2 (45) NULL ,
	USER_4 NVARCHAR2 (45) NULL ,
	USER_5 NVARCHAR2 (45) NULL ,
	USER_6 NVARCHAR2 (45) NULL ,
	USER_7 NVARCHAR2 (45) NULL ,
	USER_8 NVARCHAR2 (45) NULL ,
	USER_9 NVARCHAR2 (80) NULL ,
	USER_10 NVARCHAR2 (80) NULL ,
	USER_11 NVARCHAR2 (45) NULL ,
	USER_12 NVARCHAR2 (45) NULL ,
	USER_13 NVARCHAR2 (45) NULL ,
	USER_14 NVARCHAR2 (45) NULL ,
	USER_15 NVARCHAR2 (45) NULL ,
	USER_16 NVARCHAR2 (45) NULL ,
	ATTID NVARCHAR2 (15) NULL ,
	ATT_1 NVARCHAR2 (45) NULL ,
	ATT_2 NVARCHAR2 (45) NULL ,
	ATT_3 NVARCHAR2 (45) NULL ,
	ATT_4 NVARCHAR2 (45) NULL ,
	ATT_5 NVARCHAR2 (45) NULL ,
	ATT_6 NVARCHAR2 (45) NULL ,
	ATT_7 NVARCHAR2 (45) NULL ,
	ATT_8 NVARCHAR2 (45) NULL ,
	ATT_9 NVARCHAR2 (80) NULL ,
	ATT_10 NVARCHAR2 (80) NULL ,
	ATT_11 NVARCHAR2 (45) NULL ,
	ATT_12 NVARCHAR2 (45) NULL ,
	ATT_13 NVARCHAR2 (45) NULL ,
	ATT_14 NVARCHAR2 (45) NULL ,
	ATT_15 NVARCHAR2 (45) NULL ,
	ATT_16 NVARCHAR2 (45) NULL ,
	RLSSTARTDATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	RLSSTOPDATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	PREVPARTID NVARCHAR2 (25) NULL ,
	CREATE_USER NVARCHAR2 (20) NULL ,
	CREATE_DATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	UPDATE_USER NVARCHAR2 (20) NULL ,
	UPDATE_DATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	ISLOCKED CHAR (1) NULL ,
	ISEXPORT CHAR (1) NULL ,
	TAG CHAR (1)   DEFAULT 'N' ,
	DTS_DATE DATE DEFAULT SYSDATE 
);
/
CREATE TABLE VPDM_SBOM (
	ROW_ID NUMBER(38)  NOT NULL PRIMARY KEY,
	NO_ID NUMBER(38)  NOT NULL ,
	PARENTTYPE CHAR (1) NOT NULL ,
	PARENTID NVARCHAR2 (25) NOT NULL ,
	PARENTVERSION NUMBER(6)  NOT NULL ,
	P_NAME NVARCHAR2 (50) NULL ,
	P_ENGLISHNAME NVARCHAR2 (100) NULL ,
	P_CHIUNIT NVARCHAR2 (20) NULL ,
	CHILDTYPE CHAR (1) NOT NULL ,
	CHILDID NVARCHAR2 (25) NOT NULL ,
	CHILDVERSION NUMBER(6) NOT NULL ,
	C_NAME NVARCHAR2 (50) NULL ,
	C_ENGLISHNAME NVARCHAR2 (100) NULL ,
	C_CHIUNIT NVARCHAR2 (20) NULL ,
	POS NVARCHAR2 (8) NULL ,
	USEQTY  NUMBER(15, 8) NULL ,
	STATUS CHAR (1) NULL ,
	BOM_ST CHAR (1) NULL ,
	BOM_NOTE  CLOB NULL ,
	BOM_NOTE1 NVARCHAR2 (512) NULL ,
	BOM_NOTE2 NVARCHAR2 (512) NULL ,		
	UBOM_NOTE2 NVARCHAR2 (512) NULL ,
	MP_VERSION NVARCHAR2 (15) NULL ,
	RLSDATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	STOPDATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	CREATE_USER NVARCHAR2 (20) NULL ,
	CREATE_DATE TIMESTAMP WITH LOCAL TIME ZONE NULL ,
	TAG CHAR (1)  DEFAULT 'N',
	DTS_DATE DATE DEFAULT SYSDATE 
);
/
        CREATE SEQUENCE VPDM_PART_SEQ
                MINVALUE 1
                INCREMENT BY 1
                START WITH 1
                NOCACHE
                NOCYCLE;
        CREATE SEQUENCE VPDM_SBOM_SEQ
                MINVALUE 1
                INCREMENT BY 1
                START WITH 1
                NOCACHE
                NOCYCLE;
/
CREATE TRIGGER BI_VPDM_PART

BEFORE INSERT ON VPDM_PART

FOR EACH ROW

BEGIN 

SELECT VPDM_PART_SEQ.NEXTVAL INTO :NEW.ROW_ID FROM DUAL;

END; 
/
CREATE TRIGGER BI_VPDM_SBOM

BEFORE INSERT ON VPDM_SBOM

FOR EACH ROW

BEGIN 

SELECT VPDM_SBOM_SEQ.NEXTVAL INTO :NEW.ROW_ID FROM DUAL;

END;
/