IF OBJECT_ID('TADC_OITM_DealValid') IS NOT NULL
	DROP PROCEDURE TADC_OITM_DealValid
GO

CREATE PROCEDURE TADC_OITM_DealValid
AS
BEGIN
	DECLARE @ItemCode AS NVARCHAR(20)
	DECLARE @AR_AVGPRICE AS NUMERIC(19,2) = 0
	DECLARE @AVGPRICE AS NUMERIC(19,2) = 0
	DECLARE @PEC AS NUMERIC(19,2) = 0
	DECLARE @PROFIT AS NUMERIC(19,2) = 0
	DECLARE @U_QUANTITY AS NUMERIC(19,6) --綪扳计秖, 
	DECLARE @U_RIN1QUANTITY AS NUMERIC(19,6) --綪癶计秖,
	DECLARE @U_PCH1QUANTITY AS NUMERIC(19,6) --秈砯计秖, 
	DECLARE @U_RPC1QUANTITY AS NUMERIC(19,6) --秈癶计秖, 
	DECLARE @FREIGHT  AS NUMERIC(19,6)		 --笲禣 = 笲 * を, 

DECLARE myBOM CURSOR FOR 
	SELECT  ItemCode FROM OITM ORDER BY ItemCode
		
OPEN myBOM
FETCH NEXT FROM myBOM into @ItemCode
WHILE (@@FETCH_STATUS =0)
	BEGIN
		SET @AR_AVGPRICE = 0
		SET @AVGPRICE = 0
		SET @PEC = 0
		SET @PROFIT = 0
		
		SET @U_QUANTITY=(
				SELECT     ISNULL(SUM(INV1.Quantity),0)
				FROM         OINV INNER JOIN
									  INV1 ON OINV.DocEntry = INV1.DocEntry
				WHERE	INV1.ItemCode=@ItemCode 
		)

		SET @U_RIN1QUANTITY=(
				SELECT     ISNULL(SUM(RIN1.Quantity),0)
				FROM         ORIN INNER JOIN
									  RIN1 ON ORIN.DocEntry = RIN1.DocEntry
				WHERE	RIN1.ItemCode=@ItemCode
		)

		SET @U_PCH1QUANTITY=(
			SELECT     ISNULL(SUM(PCH1.Quantity),0)
			FROM         OPCH INNER JOIN
								  PCH1 ON OPCH.DocEntry = PCH1.DocEntry
			WHERE	PCH1.ItemCode=@ItemCode
		)

		SET @U_RPC1QUANTITY=(
			SELECT     ISNULL(SUM(RPC1.Quantity),0)
			FROM         ORPC INNER JOIN
								  RPC1 ON ORPC.DocEntry = RPC1.DocEntry
			WHERE	RPC1.ItemCode=@ItemCode
		)

		--┮ΤA/R祇布ぇキА虫基
		SET @AR_AVGPRICE=(
				SELECT     AVG(INV1.Price)
				FROM         OINV INNER JOIN
									  INV1 ON OINV.DocEntry = INV1.DocEntry
				WHERE	INV1.ItemCode=@ItemCode 
		)

		--兜ヘΘセ-ぃだ
		SET @AVGPRICE=(
			SELECT AVG(AvgPrice) FROM OITW WHERE ItemCode=@ItemCode
		)

		--柬ゑ
		IF (@AR_AVGPRICE <>0 AND @AVGPRICE<>0 )
		BEGIN
			SET @PROFIT = (@AR_AVGPRICE - @AVGPRICE ) / @AR_AVGPRICE
		END

		--綪扳κだゑ
		IF ((@U_QUANTITY - @U_RIN1QUANTITY<>0) AND (@U_PCH1QUANTITY - @U_RPC1QUANTITY<>0))
		BEGIN
			SET @PEC = (@U_QUANTITY - @U_RIN1QUANTITY) / (@U_PCH1QUANTITY - @U_RPC1QUANTITY) * 100
		END
		
		--笲禣
		SET @FREIGHT = (SELECT     [@FREIGHT].U_SHIPPING_PRICE* OITM.SWeight1
						FROM         OITM INNER JOIN
						OCRD ON OITM.CardCode = OCRD.CardCode INNER JOIN
						[@FREIGHT] ON OCRD.U_FREIGHT = [@FREIGHT].Code 
						WHERE OITM.ItemCode =@ItemCode 
						)
		
		UPDATE OITM SET
						U_QUANTITY=@U_QUANTITY,
						U_RIN1QUANTITY=@U_RIN1QUANTITY,
						U_PCH1QUANTITY=@U_PCH1QUANTITY,
						U_RPC1QUANTITY=@U_RPC1QUANTITY,
						U_SALEPERCEN=@PEC,
						U_PROFIT=@PROFIT,
						U_ITEMFREIGHT=@FREIGHT
		WHERE ItemCode =@ItemCode

		FETCH NEXT FROM myBOM into @ItemCode
	END 
CLOSE myBOM
DEALLOCATE myBOM

END